### ISSUE TITLE
Таблица "Рейтинг Акций Мозговик"

### ISSUE THREAD

**Issue by BDemetrix** [BDemetrix/BDemetrix.github.io#19]

**Comment by kulbergArt** [comment]
У нас есть платная аналитика, и там у нас есть табличка с рейтингом по компаниям.

Вова её попытался собрать, но там страхолюдище получилось. Тим просит сделать нормально. Я в Фигме нарисовал, как это выглядит, но по идее бы использовать уже созданный тобой дизайн.

[sMart-lab.ru - рейтинг акций Мозговик](https://smart-lab.ru/stocks-rating/new)
Чтобы посмотреть таблицу, войди под моим логином и паролем: kulberg kpD-4Ma-xGR-Cqu

Дизайн: [Artem Smart-lab](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=2789%3A18&mode=design&t=zz6llV3c0FnsuO7I-1)

![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/d1c19de4-6ec9-4df4-b263-19f344f28629)

**Comment by kulbergArt** [comment]
Дим, там были пожелания Тима, и я их отразил в дизайне, но забыл написать в ТЗ:

1) Закрепляться должен только столбик с тикерами. Столбик с названием компаний должен идти второй, и при скролле скрываться.

2) Ширина столбцов по возможности одинаковая, как в дизайне.  Когда ширина зависит от шапки столбца, получается некрасиво.

3) Убери, пожалуйста этот пустой столбец.

4) Последние два стобца, скорее всего должны быть с иконками, тут подождём что Тим скажет.

**Comment by kulbergArt** [comment]
иконка ссылки

![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/a75601f8-0ba8-452b-8164-b82188984a6f)

**Comment by BDemetrix** [comment]
**комменатий для Вовы**

PR привязаны к задаче
DEMO https://bdemetrix.github.io/sl_mobile/build/stocks-rating.html

Дописал изменения в скрипт для таблицы. Теперь если надо будет задать минимальную ширину колонки (лучше минимальную, чтоб динамический контент не ломал ветстку), надо прописать самой верхней ячейке задать ее в стилях инлайн, например: `<th style="min-width: 100px;">` . класс для всех ячеек этой колонки для ширины теперь не нужен

**Comment by kulbergArt** [comment]
Дим, нужно ещё небольшое обновление сделать:
Актуальный вид таблицы сделал в дизайне. 



![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/4399f4bf-62b8-42f7-9833-03a8c8fd98b5)

**Comment by BDemetrix** [comment]
> Актуальный вид таблицы сделал в дизайне.

Артем, на такие дополнения пиши пожалуйста тикет, это требует времени и возможно будет сделано не сразу, а в комментах либо потеряется либо задача в основной части будет висеть.
Сейчас таблицу уже можно исправить.
А раскрашу потом.
