### ISSUE TITLE
Заголовок в ленте

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#22]
**Задача:** сверстать заголовок для лент.
**Дизайн:** [Artem Smart-lab](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=3%3A1239&mode=design&t=AOqMrswX6uVqUbbS-1)(раздел ленты “новости“)
**Нюанс:** Этот заголовок может подставляться не всегда. Надо сверстать его так, чтобы если он не используется, всё было по прежнему

**Comment by BDemetrix** [comment]
@kulbergArt 
1. оставить минимальное расстояние между иконкой и датой не получится так ка дата всегда имеет разную длину, а чтобы обрезать слишком длинное имя надо к чему-то привязываться.
2, Владимиру надо убрать костыль, который он сам добавил в css где-то ниже по коду:
``` 
.news-card__date
{
	width: 150px;
	flex: 0 0 150px;
}
```
