### ISSUE TITLE
Блок "Что вы писали в этот день в прошлом"

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#23]
**Задача:** сверстать блок “thisday“
**Дизайн:** [Artem Smart-lab](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=2607%3A193&mode=design&t=8pxpE2UMth30ITeq-1)
**Пояснения:** в посте “thisday“ показываются посты, которые были написаны в этот день в прошлом. Пишется заголовок, дата, количество добавлений в избранное и лайки. Заголовок поста является ссылкой, каждый пост в посте тоже является ссылкой. Лайки и избранное не кликабельные.

**Comment by BDemetrix** [comment]
@kulbergArt 
что значит `каждый пост в посте тоже является ссылкой` ?
Каждая карточка в истории(списке) является ссылкой (тогда заголовок не имеет смысла делать ссылкой)?

**Comment by BDemetrix** [comment]
Задача https://github.com/BDemetrix/BDemetrix.github.io/issues/23
Верстка https://bdemetrix.github.io/sl_mobile/build/blog.html
