### ISSUE TITLE
Новый блок "Читайте на Смартлабе"

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#25]
**Проблема:** после прочтения поста, мы никаких новых постов пользователям не предлагаем.

**Задача:** сверстать блок как в дизайне =) Располагаться он должен после комментариев.

**Дизайн:** [Artem Smart-lab](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=1050%3A1944&t=tOyri4uJixSV1OSG-1)

**Нюансы:** вопрос только к картинкам в превью. Надо сделать как в дизайне, чтобы высота и ширина фиксировалась, а изображение внутри контейнера центрировалось. Криво как-то сказал xD

**Comment by BDemetrix** [comment]
@kulbergArt  забыл создать ветку   
Вот коммит: https://github.com/BDemetrix/BDemetrix.github.io/commit/83950a65faeb015f0339fffb1027932b2583aa8e

**Comment by kulbergArt** [comment]
Спасибо! Будем пробовать накатывать!

**Comment by kulbergArt** [comment]
Сделай пожалуйста у заголовков шрифт 21px (font-size: 21px;)



![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/7d55765e-c3d4-47ec-9ccc-32a92cf7c35c)

**Comment by BDemetrix** [comment]
@kulbergArt 
У нас есть важный критерий разработки, которого мы изо всех сил стараемся придерживаться: 
**максимально переиспользовать код и не плодить бесконечное количество стилей!**

Исходя из этого я сверстал этот блок из готовых компонентом внеся некоторые изменения для адаптации.
За основу я взял блок `news-card`.  Со всеми уже сверстанными эффектами (ховер, посещенная ссылка, обрезка заголовка - максимум три строки...)

![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/64604742/40ef2964-907a-4543-b571-631cf12effdb)
https://bdemetrix.github.io/sl_mobile/build/news-feed.html

Выглядит новый блок вот так со шрифтом 16px.  

![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/64604742/e813156d-67f7-4259-bed2-1f666d7579ab)
   
   
Чтобы много новых стилей не добавлять, можно увеличить его до 20px (на мой взгляд смотрится плохо):   

![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/64604742/09a06205-0c52-4c7e-94bd-56c39b894a32)


Вообще у нас есть диссонанс в размерах с точки зрения юзабилити - там где надо сделать кнопки минимум 32х32, чтобы пальцами попадать, мы делаем из 10х10, а текст который хорошо читается при 16 и выделяется на общем фоне за счет дизайна мы хотим увеличить до гигантских размеров.

**Comment by kulbergArt** [comment]
Слова Тима "Ну если Дима против, оставим так"
