### ISSUE TITLE
Поиск в профиле в мобильной версии

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#26]
**Задача:** сверстать меню в профиле пользователя.
**Пример блога:** [Блог пользователя Тимофей Мартынов](https://smart-lab.ru/mobile/users/dr-mart/blog/)
**Дизайн:** [Artem Smart-lab](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?node-id=1258%3A213&t=4VctVTXB6qMGRzTS-1)
**Нюансы:** поскольку приходится рисовать на скриншотах (из-за постоянно изменчивости дизайна) то некоторые отступы должны быть несколько иными, в отличие от того что есть в дизайне. Такие отступы я выделил красного цвета стрелочками и подписью.

Иконки приложил.

![ogl-blog](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/a9b6dd48-3122-43ad-9f2b-5386443e7993)

**Comment by BDemetrix** [comment]
@kulbergArt подскажи, 

![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/64604742/f36ef2cd-addf-454a-a0ef-3f1557c63c96)

-  это кнопка или ссылка или ...

**Comment by kulbergArt** [comment]
@BDemetrix 

Это короче та же ссылка, что и в старой версии. 
![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/2660bb9b-6f6e-46a5-870d-b8424d2d28a0)

И ведёт на оглавление блога https://smart-lab.ru/my/dr-mart/tree/

**Comment by BDemetrix** [comment]
@kulbergArt   
Верстка https://bdemetrix.github.io/sl_mobile/build/post.html
PR https://github.com/BDemetrix/BDemetrix.github.io/pull/62
