### ISSUE TITLE
Возвращение назад в слайдере через активный элемент

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#36]
1) Заходим сюда, в корпоративные облигации: https://smart-lab.ru/q/bonds/
2) Дальше открываем в таблице любую облигацию, пусть первую: https://smart-lab.ru/q/bonds/RU000A1062M5/
3) И если человек хочет вернуться назад к списку облигаций он сразу нажимает на "Корпоративные", но этот пункт уже не работает, так как находится в активном состоянии.

**Comment by BDemetrix** [comment]
@kulbergArt   
По умолчанию ссылка в текущем пункте `selector-links__item._active` не активна.   
Для того, чтобы она была активна надо в добавить ей модификатор `.selector-links__item--has-active-link`   
Сделано так потому, что это может быть нужно только на конкретных страницах и в конкретных пунктах, а не во всех.   
Следовательно в шаблоне  https://smart-lab.ru/q/bonds/RU000A1062M5/  пункт "Корпоративные" надо сделать таким:
```
<li class="selector-links__item selector-links__item--has-active-link swiper-slide _active swiper-slide-next" role="group" aria-label="2 / 8">
	<a href="/q/bonds/">Корпоративные</a>
</li>
```
   
По умолчанию ссылки активных элементов (текущих вкладок) должны быть активными или как сейчас и как я написал в комментариях?   

Дело в интуитивном поведении пользователей   
   
Если им удобно, чтоб пункты оставались кликабельными всегда и при клике на уже выбранный пункт страница перезагружалась, то лучше сделать их кликабельными по умолчанию, а для отключения кликабельности добавлять модификатор конкретному пункту.    
Если пользователю так удобно, то будет меньше кода если сделать кликабельными по умолчанию 
    
Сейчас у нас по умолчанию текущие пункты не кликабельны и их поведение надо менять с помощью модификатора.

**Comment by kulbergArt** [comment]
@BDemetrix 
Тим решил, что элемент в меню должен быть активен всегда.

**Comment by BDemetrix** [comment]
@kulbergArt 
По умолчанию ссылка в текущем пункте (с классом _active) активна,  но при необходимости перехода можно запретить  добавив модификатор `.selector-links__item--none-link-events`
