### ISSUE TITLE
Ссылка в заголовке некоторых блоков

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#43]
У нас есть такой заголовок у некоторых блоков. И иногда там будет находится ссылка на страницу.

Надо прописать класс так, чтобы если там была ссылка, то появлялось подчёркивание (underline).

На данный момент мы ссылку ставим, но не понятно, что это ссылка.

И если ссылки нет, то и подчёркивания не должно быть, что логично)

![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/3777dc1b-8966-43cc-9238-f41cff24684d)

**Comment by BDemetrix** [comment]
Верстка https://bdemetrix.github.io/sl_mobile/build/
