### ISSUE TITLE
Переработка заголовков и меню в лентах

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#54]
Дим, к сожалению пришла задача по переделыванию того, что есть. Речь идёт о заголовках к странице, и сопутствующему ему меню.
Дизайн:  [Фигма](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=3%3A1239&mode=design&t=AgClmbVBtNOpFJ09-1)

![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/0449cc00-0e44-4619-b577-f190f4a0ab34)

**Comment by BDemetrix** [comment]
@kulbergArt прошу уточнить как будут выглядеть раскрытые фильтры
Тоже на белом фоне (как заголовок в этой задаче) или как сейчас (скриншот)?


![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/64604742/b4486c87-2244-4f07-b1c5-5873eee5794f)

**Comment by kulbergArt** [comment]
Давай внизу сделаем, под плашкой на сером фоне.
![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/54521ab0-63fb-47f3-90e0-f0c91a697662)

**Comment by kulbergArt** [comment]
Добавил фрейм с раскрытым меню

**Comment by BDemetrix** [comment]
@kulbergArt 
Задача https://github.com/BDemetrix/BDemetrix.github.io/issues/54  
Верстка https://bdemetrix.github.io/sl_mobile/build/news-premium.html

**Comment by BDemetrix** [comment]
@kulbergArt добавил поиск
