### ISSUE TITLE
Добавляем кнопки для скачивания приложения в футер

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#58]
Нужно добавить ещё две кнопки для скачивания приложения смартлаба в футер.

И чтобы было красиво)

Дизайн: [Фигма](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=1634%3A57&mode=design&t=jyEeDaHvfM8zximQ-1)

![ag](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/68da4ef5-c4cd-4ccd-a1e4-3bf9999ceab5)
![rs](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/e32e70f5-3b01-4883-a6aa-f08bc70d50cf)

https://apps.rustore.ru/app/ru.smartlab
https://appgallery.huawei.com/#/app/C109059143

**Comment by BDemetrix** [comment]
@kulbergArt   
Верстка:   
- широкий футор https://bdemetrix.github.io/sl_mobile/build/quotes.html  
- узкий футор https://bdemetrix.github.io/sl_mobile/build/
