### ISSUE TITLE
Цитирование в комментариях

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#59]
У нас в комментариях есть есть возможность ввести цитату из поста, и в мобильной версии нет для неё дизайна.

Цитата в коде поста вставляется просто в теге <blockquote></blockquote>, нужно класс подвязать к этому тегу, видимо =)

Дизайн: [Фигма](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=185%3A57&mode=design&t=5kDV9nxgtBoWMdKW-1)

![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/f0276be3-7f9b-48ed-857c-9e14d6c59a1a)

![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/9c003f0f-14b5-4f52-a215-ce3bcffb57d0)

**Comment by BDemetrix** [comment]
@kulbergArt 
PR: https://github.com/BDemetrix/BDemetrix.github.io/pull/64
Верстка https://bdemetrix.github.io/sl_mobile/build/post.html
  
![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/64604742/53c07517-04be-4a38-b201-b768750e4c99)

**Comment by kulbergArt** [comment]
Кавычки слишком близко к цитате.


![Image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/fda29267-7a0a-47d6-8c5a-acad6ab665ea)

**Comment by kulbergArt** [comment]
Спасибо!
