### ISSUE TITLE
Маленькое обновление для issues/23

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#63]
Была задача: https://github.com/BDemetrix/BDemetrix.github.io/issues/23

Сейчас есть косяк в том, что если нет лайков и добавлений в избранное, то Вова просто эти показатели не выводит.

Я изменил третью плашку, чтобы отразить как это должно быть в данном случае.

[Дизайн](https://www.figma.com/file/wk6Gcd36p17NDhlP0VjHod/Artem-Smart-lab?type=design&node-id=2607%3A193&mode=design&t=5pskRnNcdCHUgaxT-1)

![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/9c4c2b1c-550a-4582-9849-f9cde2af022f)

**Comment by BDemetrix** [comment]
@kulbergArt а в чем собственно задача?
Нули вывести?
Вот:
```
<button class="post-card__btn post-card__btn--favorite" type="button" disabled>
            <svg width="19" height="18">
                <use xlink:href="images/icons/post-card/sprite.svg#star"></use>
            </svg>
            <span class="post-card__btns-count">0</span>
</button>
```

чтобы кнопка была не активной добавить атрибут `disabled`
