### ISSUE TITLE
Возвращение к блудному сыну (окну модерации)

### ISSUE THREAD

**Issue by kulbergArt** [BDemetrix/BDemetrix.github.io#66]
В окне модерации в мобиле есть некоторый недостаток в понимании что сейчас активно, а что нет. Да и стили прыгают. Давай цвета подвигаем =) Знаю ты это не очень любишь)

Фрейм: "popup clear desktop new colors"

Меняем только цвета у активных и не активных элементов (кнопки, теги). Шрифты, font-weight и что ещё может отличаться не трогаем.

Ссылка: [Figma](https://www.figma.com/file/8Fzm2HQVRU4sSF12Vt0piv/Smart_Lab-with-Tema?type=design&node-id=0%3A1&mode=design&t=E6zlrfkXv2SPBesF-1)

![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/111301254/d8ab0915-72b7-483c-a0ab-ccd02c6527c8)

**Comment by BDemetrix** [comment]
@kulbergArt прошу объяснить значение `недостаток в понимании что сейчас активно, а что нет` 
Имеешь в виду, что не нажимается (например у кнопки атрибут disabled) или не выбран (как чекбокс без checked)?
Нет темной темы!

**Comment by BDemetrix** [comment]
@kulbergArt  
Создан глобальный класс `.search-field-with-icon` - необходимо заменить добавить его в html ко всем `.nf-filter__search
`Пример `class="nf-filter__search search-field-with-icon"`

Сделать голубые кнопки `.blue-btn` серыми можно двумя способами:
1) добавить атрибут `disabled` - кнопка станет не активной
2) Добавить модификатор `.blue-btn--not-selected` - кнопка останется активной

**Comment by kulbergArt** [comment]
> @kulbergArt прошу объяснить значение `недостаток в понимании что сейчас активно, а что нет` Имеешь в виду, что не нажимается (например у кнопки атрибут disabled) или не выбран (как чекбокс без checked)? Нет темной темы!

Имеются ввиду все элементы которые могут быть активными или нет. К примеру, модератор вывел пост на главную ленту. Кнопка "Главная" изначально была "серая", а когда пост был выведен на главную стала "синей".

Тогда модератор открывает снова это окно, ему сразу будет видно какой пот выведен, какой тег поставлен и т.д.

До этого, ему приходилось вглядываться, и зачастую вызывало ошибки в использовании.

**Comment by BDemetrix** [comment]
@kulbergArt для этого надо использовать модификатор `.blue-btn--not-selected`
Хотя я учел оба варианта  
  
Только надо исправить стили для  (развернут/свернут)
![image](https://github.com/BDemetrix/BDemetrix.github.io/assets/64604742/355412d6-b6cd-4f1a-8ba2-a4f8838285ec)

**Comment by BDemetrix** [comment]
@kulbergArt готово
Коммиты 
https://github.com/BDemetrix/BDemetrix.github.io/pull/68
https://github.com/BDemetrix/BDemetrix.github.io/pull/69
